version: '3.8'

networks:
  aboutme_network:
    driver: bridge
    name: aboutme_app_net

services:
  content_server:
    build: ./content
    container_name: aboutme_content_server
    networks:
      - aboutme_network
    restart: unless-stopped

  spotlight_api:
    build: ./SpotlightCacheService
    container_name: aboutme_spotlight_api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - spotlight_cache_data:/app/cache
    networks:
      - aboutme_network
    restart: unless-stopped

volumes:
  spotlight_cache_data: {}